# Generated by Django 5.0.6 on 2025-11-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('crop', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('prevention', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='disease_images/')),
            ],
        ),
    ]
