# Generated by Django 5.0.6 on 2025-11-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiseaseInfo',
        ),
    ]
